WebsiteLibrary/Models/Book.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebsiteLibrary.Models
{
    public class Book
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "{0} Không được để trống")]
        [StringLength(maximumLength: 500, MinimumLength = 1, ErrorMessage = "{0} Không được nhỏ hơn {2} và vượt quá {1}")]
        public string NameOfBook { get; set; }

        [Required(ErrorMessage = "{0} Không được để trống")]
        [StringLength(maximumLength: 500, MinimumLength = 1, ErrorMessage = "{0} Không được nhỏ hơn {2} và vượt quá {1}")]
        public string Author { get; set; }

        [Required(ErrorMessage = "{0} Không được để trống")]
        [Range(1, Int32.MaxValue)]
        public int YearOfPrint { get; set; }

        [Required(ErrorMessage = "{0} Không được để trống")]
        [StringLength(maximumLength: 20, MinimumLength = 4, ErrorMessage = "{0} Không được nhỏ hơn {2} và vượt quá {1}")]
        public string Code { get; set; }

        [Required(ErrorMessage = "{0} Không được để trống")]
        [Range(1, Int32.MaxValue)]
        public int Quantity { get; set; }

        [Required(ErrorMessage = "{0} Không được để trống")]
        public int CategoryId { get; set; }

        public string ImageName { get; set; }

        [ForeignKey("CategoryId")]
        public virtual Category Category { get; set; }
    }
}

WebsiteLibrary/ViewModels/Book/BookPageViewModel.cs
using System;
using System.Collections.Generic;

namespace WebsiteLibrary.ViewModels
{
    public class BookPageViewModel
    {
        public PaginationViewModel Page { get; set; }

        public IEnumerable<BookViewModel> Books { get; set; }

        public IEnumerable<CategoryViewModel> Categories { get; set; }
    }
}

WebsiteLibrary/ViewModels/Book/BookViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using WebsiteLibrary.Models;

namespace WebsiteLibrary.ViewModels
{
    public class BookViewModel
    {
        public int Id { get; set; }

        public string NameOfBook { get; set; }

        public string Author { get; set; }

        public int YearOfPrint { get; set; }

        public string Code { get; set; }

        public int Quantity { get; set; }

        public string CategoryName { get; set; }

        public string ImageName { get; set; }

        public static BookViewModel BookView(Book bookView)
        {
            var a = new BookViewModel();
            a.NameOfBook = bookView.NameOfBook;
            a.Author = bookView.Author;
            a.Id = bookView.Id;
            a.YearOfPrint = bookView.YearOfPrint;
            a.Code = bookView.Code;
            a.Quantity = bookView.Quantity;
            a.CategoryName = bookView.Category.CategoryName;
            a.ImageName = bookView.ImageName;
            return a;
        }

        public static IEnumerable<BookViewModel> BookViews(IEnumerable<Book> books)
        {
            List<BookViewModel> bookViews = new List<BookViewModel>();
            for (int i = 0; i < books.Count(); i++)
            {
                bookViews.Add(BookView(books.ElementAtOrDefault(i)));
            }

            return bookViews;
        }
    }
}

WebsiteLibrary/ViewModels/Book/CreateBookViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebsiteLibrary.ViewModels
{
    public class CreateBookViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "{0} Không được để trống")]
        [StringLength(maximumLength: 500, MinimumLength = 1, ErrorMessage = "{0} Không được nhỏ hơn {2} và vượt quá {1}")]
        [Display(Name = "Tên Sách *")]
        public string NameOfBook { get; set; }

        [Required(ErrorMessage = "{0} Không được để trống")]
        [StringLength(maximumLength: 500, MinimumLength = 1, ErrorMessage = "{0} Không được nhỏ hơn {2} và vượt quá {1}")]
        [Display(Name = "Tên Tác Giả *")]
        public string Author { get; set; }

        [Required(ErrorMessage = "{0} Không được để trống")]
        [Range(1, Int32.MaxValue)]
        [Display(Name = "Năm Xuất Bản *")]
        public int YearOfPrint { get; set; }

        [Required(ErrorMessage = "{0} Không được để trống")]
        [StringLength(maximumLength: 20, MinimumLength = 4, ErrorMessage = "{0} Không được nhỏ hơn {2} và vượt quá {1}")]
        [Display(Name = "Mã Sách *")]
        public string Code { get; set; }

        [Required(ErrorMessage = "{0} Không được để trống")]
        [Range(1, Int32.MaxValue)]
        [Display(Name = "Số Lượng *")]
        public int Quantity { get; set; }

        [Display(Name = "Ảnh")]
        public IFormFile Image { get; set; }

        public IEnumerable<SelectListItem> Categories { get; set; }

        [Display(Name = "Thể Loại *")]
        [Required(ErrorMessage = "{0} Không được để trống")]
        public int CategoryId { get; set; }
    }
}

WebsiteLibrary/ViewModels/Book/DetailsBookViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebsiteLibrary.ViewModels
{
    public class DetailsBookViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Tên Sách: ")]
        public string NameOfBook { get; set; }

        [Display(Name = "Tên Tác Giả: ")]
        public string Author { get; set; }

        [Display(Name = "Năm Xuất Bản: ")]
        public int YearOfPrint { get; set; }

        [Display(Name = "Mã Sách: ")]
        public string Code { get; set; }

        [Display(Name = "Số Lượng")]
        public int Quantity { get; set; }

        [Display(Name = "Ảnh: ")]
        public string Photo { get; set; }

        public IEnumerable<SelectListItem> Categories { get; set; }

        [Display(Name = "Thể Loại")]
        public int CategoryId { get; set; }
    }
}

WebsiteLibrary/ViewModels/Book/UpdateBookViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebsiteLibrary.ViewModels
{
    public class UpdateBookViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "{0} Không được để trống")]
        [StringLength(maximumLength: 500, MinimumLength = 1, ErrorMessage = "{0} Không được nhỏ hơn {2} và vượt quá {1}")]
        [Display(Name = "Tên Sách *")]
        public string NameOfBook { get; set; }

        [Required(ErrorMessage = "{0} Không được để trống")]
        [StringLength(maximumLength: 500, MinimumLength = 1, ErrorMessage = "{0} Không được nhỏ hơn {2} và vượt quá {1}")]
        [Display(Name = "Tên Tác Giả *")]
        public string Author { get; set; }

        [Required(ErrorMessage = "{0} Không được để trống")]
        [Range(1, Int32.MaxValue)]
        [Display(Name = "Năm Xuất Bản *")]
        public int YearOfPrint { get; set; }

        [Required(ErrorMessage = "{0} Không được để trống")]
        [StringLength(maximumLength: 20, MinimumLength = 4, ErrorMessage = "{0} Không được nhỏ hơn {2} và vượt quá {1}")]
        [Display(Name = "Mã Sách *")]
        public string Code { get; set; }

        [Required(ErrorMessage = "{0} Không được để trống")]
        [Range(1, Int32.MaxValue)]
        [Display(Name = "Số Lượng *")]
        public int Quantity { get; set; }

        [Display(Name = "Ảnh")]
        public string Photo { get; set; }

        public IFormFile Image { get; set; }

        public IEnumerable<SelectListItem> Categories { get; set; }

        [Display(Name = "Thể Loại *")]
        [Required(ErrorMessage = "{0} Không được để trống")]
        public int CategoryId { get; set; }
    }
}

WebsiteLibrary/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using WebsiteLibrary.Models;
using WebsiteLibrary.ViewModels;

namespace WebsiteLibrary.Controllers
{
    public class BookController : Controller
    {
        private readonly ILogger<BookController> _logger;
        private readonly WebsiteLibraryContext _dbContext;
        private readonly IWebHostEnvironment _webHostingEnvironment;
        private readonly IMapper _mapper;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public BookController(IMapper mapper, UserManager<User> userManager, SignInManager<User> signInManager, ILogger<BookController> logger,
                                IWebHostEnvironment webHostingEnvironment, WebsiteLibraryContext dbContext)
        {
            _logger = logger;
            _mapper = mapper;
            _userManager = userManager;
            _signInManager = signInManager;
            _dbContext = dbContext;
            _webHostingEnvironment = webHostingEnvironment;
        }

        [Authorize]
        public IActionResult Books(string searchString, string sortOrder, int? category, int currentPage = 1, int pageSize = 5)
        {

            #region search

            IQueryable<Book> books = _dbContext.BooksList.Include(x => x.Category);

            IQueryable<Category> categories = _dbContext.CategoriesList;


            if (category.HasValue)
            {
                books = books.Where(x => x.CategoryId == category);
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                books = books.Where(s => s.NameOfBook.Contains(searchString)
                || s.Author.Contains(searchString)
                || s.Code.Contains(searchString));
            }

            #endregion

            #region Phần tử
            int totalItems = books.Count();
            int totalPages;
            if (totalItems / pageSize == 0)
            {
                totalPages = totalItems / pageSize;
            }
            else
            {
                totalPages = (totalItems / pageSize) + 1;
            }

            if (currentPage > totalPages)
            {
                currentPage = totalPages;
                if (currentPage == 0)
                {
                    currentPage = 1;
                }
            }
            #endregion

            #region Số trang trước sau
            int startPage = 1;
            int endPage = totalPages;
            int displayPage = 6;
            bool isOdd = displayPage % 2 != 0;
            int leftPage = displayPage / 2;
            int rightPage = displayPage / 2;

            if (!isOdd)
            {
                rightPage = (int)Math.Floor((decimal)displayPage / 2);
                leftPage = rightPage - 1;
            }

            if (currentPage <= startPage + leftPage)
            {
                endPage = startPage + (displayPage - 1);
            }
            else if (currentPage >= endPage - rightPage)
            {
                startPage = endPage - (displayPage - 1);
            }
            else
            {
                startPage = currentPage - leftPage;
                endPage = currentPage + rightPage;
            }

            if (endPage > totalPages)
            {
                endPage = totalPages;
            }

            if (startPage < 1)
            {
                startPage = 1;
            }
            #endregion

            #region Tạo Sắp Xếp Giá Trị 1 Thuộc Tính

            ViewBag.SortNameBook = String.IsNullOrEmpty(sortOrder) ? "name_desc" : string.Empty;

            ViewBag.SortAuthor = sortOrder == "author_asc" ? "author_desc" : "author_asc";
            ViewBag.SortYear = sortOrder == "year_asc" ? "year_desc" : "year_asc";
            ViewBag.SortCode = sortOrder == "code_asc" ? "code_desc" : "code_asc";
            ViewBag.SortQuantity = sortOrder == "quantity_asc" ? "quantity_desc" : "quantity_asc";
            ViewBag.SortCategory = sortOrder == "category_asc" ? "category_desc" : "category_asc";

            switch (sortOrder)
            {
                case "name_desc":
                    books = books.OrderByDescending(s => s.NameOfBook);
                    break;

                case "author_desc":
                    books = books.OrderByDescending(s => s.Author);
                    break;
                case "author_asc":
                    books = books.OrderBy(s => s.Author);
                    break;

                case "year_desc":
                    books = books.OrderByDescending(s => s.YearOfPrint);
                    break;
                case "year_asc":
                    books = books.OrderBy(s => s.YearOfPrint);
                    break;

                case "code_desc":
                    books = books.OrderByDescending(s => s.Code);
                    break;
                case "code_asc":
                    books = books.OrderBy(s => s.Code);
                    break;

                case "quantity_desc":
                    books = books.OrderByDescending(s => s.Quantity);
                    break;
                case "quantity_asc":
                    books = books.OrderBy(s => s.Quantity);
                    break;

                case "category_desc":
                    books = books.OrderByDescending(s => s.Category.CategoryName);
                    break;
                case "category_asc":
                    books = books.OrderBy(s => s.Category.CategoryName);
                    break;
                default:
                    books = books.OrderBy(s => s.NameOfBook);
                    break;
            }
            #endregion

            books = books.Skip((currentPage - 1) * pageSize)
                    .Take(pageSize);

            return View(new BookPageViewModel
            {
                Page = new PaginationViewModel
                {
                    CurrentPage = currentPage,
                    EndPage = endPage,
                    StartPage = startPage,
                    TotalPages = totalPages,
                    PageSize = pageSize
                },
                Books = BookViewModel.BookViews(books),

                Categories = CategoryViewModel.CategoryViews(categories),
            });
        }

        #region Create Book
        [HttpGet]
        public IActionResult CreateBook()
        {
            ViewBag.Categories = _dbContext.CategoriesList.Select(x => new SelectListItem
            {
                Text = x.CategoryName,
                Value = $"{x.Id}",
            }).ToList();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateBook(CreateBookViewModel createBook, IFormFile image)
        {

            if (_dbContext.BooksList.Any(x => x.Code == createBook.Code))
            {
                ModelState.AddModelError(string.Empty, "Mã cuốn sách đã tồn tại trong kho");
            }

            if (!ModelState.IsValid)
            {
                ViewBag.Categories = _dbContext.CategoriesList.Select(x => new SelectListItem
                {
                    Text = x.CategoryName,
                    Value = $"{x.Id}",
                }).ToList();

                return View(createBook);
            }

            string uniqueFileName = null;
            if (createBook.Image != null)
            {
                string uploadsFolder = Path.Combine(_webHostingEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + createBook.Image.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                createBook.Image.CopyTo(new FileStream(filePath, FileMode.Create));
            }

            await _dbContext.BooksList.AddAsync(new Book
            {
                Code = createBook.Code,
                Author = createBook.Author,
                CategoryId = createBook.CategoryId,
                NameOfBook = createBook.NameOfBook,
                Quantity = createBook.Quantity,
                YearOfPrint = createBook.YearOfPrint,
                ImageName = uniqueFileName,
            });

            _dbContext.SaveChanges();
            return RedirectToAction("Books");
        }
        #endregion

        #region Update Book
        [HttpGet]
        public IActionResult UpdateBook(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                var currentBook = _dbContext.BooksList.FirstOrDefault(x => x.Id == id);

                ViewBag.Categories = _dbContext.CategoriesList.Select(x => new SelectListItem
                {
                    Text = x.CategoryName,
                    Value = $"{x.Id}",
                    Selected = currentBook.CategoryId == x.Id
                }).ToList();

                return View(new UpdateBookViewModel
                {
                    Id = currentBook.Id,
                    Code = currentBook.Code,
                    Author = currentBook.Author,
                    CategoryId = currentBook.CategoryId,
                    NameOfBook = currentBook.NameOfBook,
                    Quantity = currentBook.Quantity,
                    YearOfPrint = currentBook.YearOfPrint,
                    Photo = currentBook.ImageName,
                });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

WebsiteLibrary/Views/Book/CreateBook.cshtml
@model CreateBookViewModel
@section Styles
{
    <style>


        div {
            font-size: 16px;
            color: #007bff;
        }
    </style>
}

@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

@section Scripts
{
    <script>$(document).ready(function () {
            $(imageUpload).on('change', function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('')
            })
        });</script>

}

@using (Html.BeginForm("createbook", "book", FormMethod.Post, new { @class = "col-md-4", enctype = "multipart/form-data" }))
{
    Html.AntiForgeryToken();
    @Html.ValidationSummary(false)
    <div class="form-group">
        <!--Gọi lại nhãn ở ViewModel hiển thị tên-->
        @Html.LabelFor(x => x.NameOfBook)
        @Html.TextBoxFor(x => x.NameOfBook, new { placeholder = "", @class = "form-control" })
        <!--Hiển thị lỗi khi k nhập đúng-->
        @Html.ValidationMessageFor(x => x.NameOfBook)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Author)
        @Html.TextBoxFor(x => x.Author, new { placeholder = "", @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Author)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.CategoryId)
        @Html.DropDownListFor(x => x.CategoryId, (IEnumerable<SelectListItem>)ViewBag.Categories, "Danh Mục", new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryId)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.YearOfPrint)
        @Html.TextBoxFor(x => x.YearOfPrint, new { placeholder = "", @class = "form-control", type = "number" })
        @Html.ValidationMessageFor(x => x.YearOfPrint)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Quantity)
        @Html.TextBoxFor(x => x.Quantity, new { placeholder = "", @class = "form-control", type = "number" })
        @Html.ValidationMessageFor(x => x.Quantity)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Code)
        @Html.TextBoxFor(x => x.Code, new { placeholder = "", @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Code)
    </div>
    <div id="imageUpload" class="form-group">
        @Html.LabelFor(x => x.Image)
        <input type="file" name="Image" />
    </div>
    <div class="form-group">(Có dấu * vui lòng điền đầy đủ thông tin)</div>
    <button type="submit" class="btn btn-primary">Tạo Mới</button>
    <button action="/book/books" type="submit" class="btn btn-primary" style="position: relative; right: -30px;">Trở Về</button>
}

WebsiteLibrary/Views/Book/DetailsBook.cshtml
@model DetailsBookViewModel
@section Styles
{
    <style>


        div {
            font-size: 16px;
            color: #007bff;
        }
    </style>
}

@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

@using (Html.BeginForm("detailsBook", "book", new { id = Model.Id }, FormMethod.Post, true, new { @class = "col-md-4" }))
{
    @Html.HiddenFor(x => x.Id);
    Html.AntiForgeryToken();

    <div class="form-group">
        @Html.LabelFor(x => x.NameOfBook)
        @Html.DisplayFor(x => x.NameOfBook, new { placeholder = "", @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Author)
        @Html.DisplayFor(x => x.Author, new { placeholder = "", @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Categories)
        @Html.DropDownListFor(x => x.CategoryId, (IEnumerable<SelectListItem>)ViewBag.Categories, "Danh Mục", new { @class = "form-control", disabled = "disabled" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.YearOfPrint)
        @Html.DisplayFor(x => x.YearOfPrint, new { placeholder = "", @class = "form-control", type = "number" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Quantity)
        @Html.DisplayFor(x => x.Quantity, new { placeholder = "", @class = "form-control", type = "number" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Code)
        @Html.DisplayFor(x => x.Code, new { placeholder = "", @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Photo)
        <img src="~/images/@Model.Photo" with="150" height="150" alt="#" />
    </div>
    @Html.ActionLink("Trở Về", "Books", "book", null, new { @class = "btn btn-primary", type = "button" })
}

WebsiteLibrary/Views/Book/UpdateBook.cshtml
@model UpdateBookViewModel
@section Styles
{
    <style>


        div {
            font-size: 16px;
            color: #007bff;
        }
    </style>
}

@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

@section Scripts
{
    <script>$(document).ready(function () {
            $(imageUpload).on('change', function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('')
            })
        });</script>

}

@using (Html.BeginForm("updatebook", "book", new { id = Model.Id }, FormMethod.Post, null, new { @class = "col-md-4", enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(x => x.Id);
    Html.AntiForgeryToken();
    @Html.ValidationSummary(false) //báo lỗi tổng khi người dùng ấn submit

    <div class="form-group">
        @Html.LabelFor(x => x.NameOfBook)
        @Html.TextBoxFor(x => x.NameOfBook, new { placeholder = "", @class = "form-control" })
        @Html.ValidationMessageFor(x => x.NameOfBook)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Author)
        @Html.TextBoxFor(x => x.Author, new { placeholder = "", @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Author)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.CategoryId)
        @Html.DropDownListFor(x => x.CategoryId, (IEnumerable<SelectListItem>)ViewBag.Categories, "Danh Mục", new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryId)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.YearOfPrint)
        @Html.TextBoxFor(x => x.YearOfPrint, new { placeholder = "", @class = "form-control", type = "number" })
        @Html.ValidationMessageFor(x => x.YearOfPrint)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Quantity)
        @Html.TextBoxFor(x => x.Quantity, new { placeholder = "", @class = "form-control", type = "number" })
        @Html.ValidationMessageFor(x => x.Quantity)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Code)
        @Html.TextBoxFor(x => x.Code, new { placeholder = "", @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Code)
    </div>
    <div id="imageUpload" class="form-group">
        @Html.LabelFor(x => x.Image)
        <img src="~/images/@Model.Photo" with="150" height="150" alt="#" />
        <input type="file" name="Image" />
    </div>
    <div class="form-group">(Có dấu * vui lòng điền đầy đủ thông tin)</div>
    <div>
        <button type="submit" class="btn btn-primary">Đồng Ý</button>
        @Html.ActionLink("Hủy", "Books", "Book", null,
                             new { @class = "btn btn-primary", type = "button", style = "position: relative; right: -30px;" })
    </div>
}